services:
  db:
    image: postgres:16-alpine
    container_name: db
    ports:
      - '5432:5432'
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: computacao_nuvem
    restart: always

